#![allow(clippy::too_many_arguments, clippy::type_complexity)]
pub mod atlas;
pub mod component;
pub mod extract;
pub mod prepare;

use bevy::prelude::*;
use bevy::render::{ExtractSchedule, RenderApp};
use bevy::ui_render::{extract_text_sections, RenderUiSystems};

use atlas::OutlineAtlas;
pub use component::TextOutline;
use extract::extract_outline_glyphs;
use prepare::prepare_outline_glyphs;

/// Adds text outline rendering to UI [`Text`] entities.
///
/// Spawn a [`TextOutline`] component alongside a UI [`Text`] node to enable outlines:
/// ```ignore
/// commands.spawn((
///     Text::new("Hello!"),
///     Node::default(),
///     TextOutline { width: 2.0, color: Color::BLACK },
/// ));
/// ```
///
/// Outlines are generated by morphologically dilating the fill glyph pixels from Bevy's
/// font atlas. The dilated bitmaps are cached in a shared [`OutlineAtlas`] and injected
/// into Bevy's UI render pipeline at a z-order just below the fill text.
pub struct TextOutlinePlugin;

impl Plugin for TextOutlinePlugin {
    fn build(&self, app: &mut App) {
        app.register_type::<TextOutline>()
            .init_resource::<OutlineAtlas>()
            .add_systems(
                PostUpdate,
                prepare_outline_glyphs,
            );

        if let Some(render_app) = app.get_sub_app_mut(RenderApp) {
            render_app.add_systems(
                ExtractSchedule,
                extract_outline_glyphs
                    .in_set(RenderUiSystems::ExtractText)
                    .before(extract_text_sections),
            );
        }
    }
}
